"""add wallet_registry and course_enrollment tables

Revision ID: 5942551dbfb2
Revises: aa1e9db24736
Create Date: 2026-05-10 20:25:02.483090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5942551dbfb2'
down_revision: Union[str, None] = 'aa1e9db24736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_enrollment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=255), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('course_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mrt_snapshot', sa.Float(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_enrollment_student_course')
    )
    op.create_index(op.f('ix_course_enrollment_course_id'), 'course_enrollment', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_enrollment_status'), 'course_enrollment', ['status'], unique=False)
    op.create_index(op.f('ix_course_enrollment_student_id'), 'course_enrollment', ['student_id'], unique=False)
    op.create_table('wallet_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=255), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('private_key_enc', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_registry_status'), 'wallet_registry', ['status'], unique=False)
    op.create_index(op.f('ix_wallet_registry_student_id'), 'wallet_registry', ['student_id'], unique=True)
    op.create_index(op.f('ix_wallet_registry_wallet_address'), 'wallet_registry', ['wallet_address'], unique=True)
    op.drop_index(op.f('idx_badge_awards_issued_by'), table_name='badge_awards')
    op.drop_index(op.f('idx_badge_awards_student'), table_name='badge_awards')
    op.drop_index(op.f('idx_badge_awards_template'), table_name='badge_awards')
    op.drop_index(op.f('idx_badge_templates_active'), table_name='badge_templates')
    op.drop_index(op.f('idx_badge_templates_created_by'), table_name='badge_templates')
    op.drop_index(op.f('ix_events_activity_id'), table_name='events')
    op.drop_index(op.f('idx_skills_name'), table_name='skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_skills_name'), 'skills', ['name'], unique=False)
    op.create_index(op.f('ix_events_activity_id'), 'events', ['activity_id'], unique=False)
    op.create_index(op.f('idx_badge_templates_created_by'), 'badge_templates', ['created_by_id'], unique=False)
    op.create_index(op.f('idx_badge_templates_active'), 'badge_templates', ['is_active'], unique=False)
    op.create_index(op.f('idx_badge_awards_template'), 'badge_awards', ['template_id'], unique=False)
    op.create_index(op.f('idx_badge_awards_student'), 'badge_awards', ['student_id'], unique=False)
    op.create_index(op.f('idx_badge_awards_issued_by'), 'badge_awards', ['issued_by_id'], unique=False)
    op.drop_index(op.f('ix_wallet_registry_wallet_address'), table_name='wallet_registry')
    op.drop_index(op.f('ix_wallet_registry_student_id'), table_name='wallet_registry')
    op.drop_index(op.f('ix_wallet_registry_status'), table_name='wallet_registry')
    op.drop_table('wallet_registry')
    op.drop_index(op.f('ix_course_enrollment_student_id'), table_name='course_enrollment')
    op.drop_index(op.f('ix_course_enrollment_status'), table_name='course_enrollment')
    op.drop_index(op.f('ix_course_enrollment_course_id'), table_name='course_enrollment')
    op.drop_table('course_enrollment')
    # ### end Alembic commands ###